### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by asmoiseenko** [Onevizion/scmdb#10]
Instead of "Updating your database" print:
SCMDB <version>

then blank line, then:
Scripts to be executed:
list of scripts

2 remove space before Executing script

3 Invalid Objects in ... - should be in yellow, like objects list

4 Instead of "Your database is up-to-date" print:
blank line
SCMDB complete

**Comment by asmoiseenko** [comment]
In 1st line add SCMDB version:
SCMBD <version number>

Print:
"No scripts to execute" when there are no new scripts

**Comment by rakrachok** [comment]
I submitted a request for this improvement, but Andrey, before applying it, I would like to clarify what exactly has to be in the first line of the SCMDB input:
SCMDB version: ${version} or SCMDB ${version}:
for ex.
SCMDB version: 1.4.1 or SCMDB 1.4.1:

Please, check out the code in the request and clarify.

**Comment by asmoiseenko** [comment]
SCMDB 1.4.1
Also, if possible do this:
SCMDB 1.4.1 SQLcl 4.2

**Comment by asmoiseenko** [comment]
Also, 
1 get rid of "PL/SQL procedure successfully completed." string after executing "compile_invalids_wrapper.sql"

2 color list of invalid object in yellow

![image](https://user-images.githubusercontent.com/13415820/27014583-d68f18d8-4f25-11e7-9f0d-8dbd10c87cc7.png)

**Comment by asmoiseenko** [comment]
Note, I've pushed some changes to master, update your fork before proceeding work

**Comment by asmoiseenko** [comment]
Can we also color error output from script to the red?
![image](https://user-images.githubusercontent.com/13415820/27030435-6d3dd344-4f96-11e7-85ca-455b6ae3b5d8.png)

**Comment by rakrachok** [comment]
> 1 get rid of "PL/SQL procedure successfully completed." string after executing "compile_invalids_wrapper.sql"
Impossible for the current implementation. I have to create 2 processes of each execution iteration  in order to do that. Now there is one command line process for sql script and compile_invalids_wrapper.sql execution. If there are 2 such processes it will cause a performance lag.

**Comment by asmoiseenko** [comment]
Think wider
https://stackoverflow.com/questions/250509/how-do-i-suppress-pl-sql-procedure-successfully-completed-message-in-sqlplus

**Comment by rakrachok** [comment]
Already have this:
`set FEEDBACK OFF
exec dbms_utility.compile_schema('&_USER._USER',false);
exec dbms_utility.compile_schema('&_USER._RPT',false);
--SET FEEDBACK ON`
But I got it, will figure it out, probably SqlCli doesn't support this option.

**Comment by asmoiseenko** [comment]
I think it should be before anonymous pl/sql block not only before calls to dbms_utility.compile_schema

**Comment by petteway** [comment]
SqlCli supports everything sqlplus does.  Fully backward compatible.  Only thing I haven't seen it do is set pagesize 0.  You might also try -S which sets silent mode which suppresses the display of the SQLcl banner, prompts, and echoing of commands.

**Comment by rakrachok** [comment]
> Can we also color error output from script to the red?
> ![image](https://user-images.githubusercontent.com/3693736/27257207-ffd2358e-53cd-11e7-907f-83f61f6ab219.png)

I'm afraid it is impossible in the current implementation or I can highlight everything will be printed out when error takes place. For ex.:
![image](https://user-images.githubusercontent.com/3693736/27257232-93ceb0aa-53ce-11e7-86ab-d2f2230f9cb1.png)
However, as you can see the script keeps being executed but further scripts will not be executed.

**Comment by rakrachok** [comment]
> 1 get rid of "PL/SQL procedure successfully completed." string after executing "compile_invalids_wrapper.sql"
> 2 color list of invalid object in yellow

done

**Comment by asmoiseenko** [comment]
after last changes we lost script output. For following scripts creates new package, we should get following output:
```
Package PKG_DL_SUPPORT compiled

Package body PKG_DL_SUPPORT compiled
```

but we got nothing
![image](https://user-images.githubusercontent.com/13415820/27770421-af754580-5f68-11e7-862e-7ae8294693e1.png)


Also missed blank line before "Invalid Objects"

**Comment by asmoiseenko** [comment]
Also, no reason to execute create.sql manually when you can't connect to DB:
![image](https://user-images.githubusercontent.com/13415820/27894957-a5320738-6239-11e7-92ab-7e8bc55c5293.png)


So, I think startup check should be executed in order:
1 make sure SQLcl is available
2 check DB connection
3 check and if needed try to create DBSCM DB objects

**Comment by asmoiseenko** [comment]
Alexander, SQLcl banner before each script pollute the output. Can we just cut it using regexp?

**Comment by petteway** [comment]
sqlcl is backwards compatible with sqlplus.  You can use regexp but better way is -S option.  That is what I've always used.

**Comment by asmoiseenko** [comment]
Scott, we tried -S, but in addition to banner it also disables output result of DDL execution. Like:

Package body created

this is valuable information, we should keep it

**Comment by rakrachok** [comment]
>Alexander, SQLcl banner before each script pollute the output. Can we just cut it using regexp?

Yes, we can. I confirm that SQLcl with option "-S" cuts away the output being printed due to DDL execution.

**Comment by asmoiseenko** [comment]
Alexander, let's implement regexp approach

**Comment by asmoiseenko** [comment]
Another minor output issue with colors:
![image](https://user-images.githubusercontent.com/13415820/28784832-bddfbf50-763e-11e7-9d88-562a7633c56a.png)

**Comment by rakrachok** [comment]
> Alexander, let's implement regexp approach
>
done

> Another minor output issue with colors
> 
done

**Comment by asmoiseenko** [comment]
One more thing. Make whole list of invalid objects colored with yellow:
![image](https://user-images.githubusercontent.com/13415820/29011906-26549494-7b61-11e7-83ba-e763cdfc7007.png)
